services:
  app:
    build:
      context: docker
      target: uffd
    volumes:
#      - ./uffd:/usr/share/uffd/uffd:ro
      - ./data:/data
      - ./config:/etc/uffd:ro
    environment:
      - FLASK_APP=/usr/share/uffd/uffd
      - CONFIG_PATH=/etc/uffd/uffd.cfg
      - UWSGI_DEB_CONFNAMESPACE=app
      - UWSGI_DEB_CONFNAME=uffd
    init: true
    command: /root/run-uffd.sh

  nginx:
    build:
      context: docker
      target: nginx
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./config/nginx-certbot.env
    volumes:
#      - ./uffd/static:/usr/share/uffd/uffd/static:ro
      - ./config/nginx:/etc/nginx/user_conf.d:ro
      - ./letsencrypt:/etc/letsencrypt

